listen:
  port: 9000

# Correspond to your reverse proxy "listen" configuration
webserver:
  https: true
  hostname: '__domain__'
  port: 443

# Your database name will be "peertube"+database.suffix
database:
  hostname: 'localhost'
  port: 5432
  suffix: '_prod'
  username: 'peertube'
  password: '__db_pwd__'

# Your object store
redis:
  hostname: 'localhost'
  port: 6379
  auth: null

# From the project root directory
storage:
  avatars: 'avatars/'
  videos: 'videos/'
  logs: 'logs/'
  previews: 'previews/'
  thumbnails: 'thumbnails/'
  torrents: 'torrents/'
  cache: 'cache/'

log:
  level: 'info' # debug/info/warning/error

cache:
  previews:
    size: 1 # Max number of previews you want to cache

admin:
  email: '__email__'

signup:
  enabled: false
  limit: 10 # When the limit is reached, registrations are disabled. -1 == unlimited

user:
  # Default value of maximum video BYTES the user can upload (does not take into account transcoded files).
  # -1 == unlimited
  video_quota: -1

# If enabled, the video will be transcoded to mp4 (x264) with "faststart" flag
# Uses a lot of CPU!
transcoding:
  enabled: false
  threads: 2
  resolutions: # Only created if the original video has a higher resolution
    240p: true
    360p: true
    480p: true
    720p: true
    1080p: true

instance:
  name: 'PeerTube'
  description: 'Welcome to this PeerTube instance!' # Support markdown
  terms: 'No terms for now.' # Support markdown
  customizations:
    javascript: '' # Directly your JavaScript code (without <script> tags). Will be eval at runtime
    css: '' # Directly your CSS code (without <style> tags). Will be injected at runtime
